name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
#   schedule:
#     - cron: "0 1 * * *"
env:
  VERSION: 1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=yunnysunny/pandoc-pdf:buildcache
          cache-to: type=registry,ref=yunnysunny/pandoc-pdf:buildcache,mode=max
          tags: |
            ${{ format('yunnysunny/pandoc-pdf:{0}', env.VERSION) }}
            yunnysunny/pandoc-pdf:latest
          build-args: |
            VERSION=${{ env.VERSION }}
      - name: Test
        run: |
          cd test
          docker run  --volume "./:/data" --rm yunnysunny/pandoc-pdf:latest \
          --metadata-file=metadata.yaml \
          a1_node_utils.md \
          a2_bibliography.md \
          -o gen.pdf --pdf-engine=weasyprint \
          --table-of-contents --toc-depth=4
      - name: Upload result of Test
        uses: actions/upload-artifact@v2
        with:
          name: result-pdf
          path: ./test/gen.pdf
      - name: Update core description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: yunnysunny/pandoc-pdf